### PR TITLE
Sprint 5: Student Profile College Assignments

### PR DESCRIPTION
**Pull request by faithyeji**
**What changed**: Created an Add College Modal and added functionality to the Colleges section of the student profile. Also added a bit of stylization  to the tailwind.config.
**New dependencies:** react-modal, @types/react-modal
**Testing** -> video
https://github.com/oliviasl/We-Are-GAME/assets/106497860/c5a15cf6-bd7e-48b9-893f-2144efcc444d

**Concerns:**
- designers wanted the search to populate as it types (how it's implemented rn), but I can change it back to a regular search button. need to consult with designers on how populate as type should look when the scale is bigger (more search terms to display o.o)
- it looks like duplicate assignments can be created (not sure if that should be accounted for in the api call or on frontend display..) 
- nits: names in our db should be fully written out (USC -> Univ of Southern California) for more accurate search representation, responsiveness still a lil janky

### CODE REVIEW

**Review by oliviasl — CHANGES_REQUESTED** [review]
Great job! The styles look great as is so we can keep it with the fill while typing. For duplicate assignments we'll prob have to alter the backend call but we'll handle that in a separate debugging ticket later.

Just one nitpick before I merge it in, can you move the AddCollegeModal.tsx to be a layout instead of a component? It's a larger piece and its own popup, so it seems to make sense as its own layout. Thanks!

**Comment by faithyeji** [comment]
It should be a layout now!

**Review by oliviasl — APPROVED** [review]
Awesome job thanks!

**Comment by carolyn-zhang** [comment]
Looks great, amazing work Yeji !!

**Pull request merged**
