### PR TITLE
Sprint 9 — Add, Edit, and Delete Mentors API's

### PR DESCRIPTION
**Pull request by greydono23**
Edits only in server.js and collegecontroller.js

Implemented createMentor, editMentor, deleteMentor

Passed testing (added, edited, and then deleted a mentor)

### CODE REVIEW

**Comment by greydono23** [comment]
@oliviasl

**Review by oliviasl — CHANGES_REQUESTED** [review]
All the code is working great! One more fix though, can you migrate all of the mentor api endpoints to the mentor controller instead of the college controller?

**Comment by greydono23** [comment]
@oliviasl haha sorry about that, migrated it to mentorController, should be all good

**Review by oliviasl — APPROVED** [review]
Good work!

**Pull request merged**
