### PR TITLE
Sprint 2: API-Users-createUser

### PR DESCRIPTION
**Pull request by mcho9434**
What changed: Added new API route to create user
New dependencies: None
Testing: Postman
Possible concerns: Please review signature and return options. I can revise if you want a different signature just lmk. Also maybe we can decide on which columns are mandatory? The code is pretty flexible around not having fields
Screenshot 2023-11-29 at 7 40 30 PM

### CODE REVIEW

**Review by oliviasl — CHANGES_REQUESTED** [review]
I added the userController to server.js to test and it looks good! The bool return is fine for now, but could you make the user_email, user_password, user_firstname and user_lastname fields all required?

**Comment by mcho9434** [comment]
Did you want those mandatory in the server code or in the sql itself? Or both?

**Comment by mcho9434** [comment]
@oliviasl

**Review by oliviasl — APPROVED** [review]
Looks good!

**Pull request merged**
