### PR TITLE
Sprint 6: edit student

### PR DESCRIPTION
**Pull request by mcho9434**
yoyo
we have most of the frontend functionality
concerns:
- What are the options for levels? 
- What do you want me to use to make Levels? The designs are assuming we have some "dropdown" component made
- What should I use to make the X for removing interests/extracirriculars
- It's not clear how interests/extracirriculars works when blank maybe some design? It j looks like any other input

If you want to get this out soon, j review for whats there. Otherwise wanna just answer the above and I'll do it? 

Try out the interests, extracirriculars,, theres a lot of state manipulation but I think it's the functionality you/Grace are looking for?

roast away on anything else ty

### CODE REVIEW

**Comment by mcho9434** [comment]
@oliviasl

**Review by oliviasl — CHANGES_REQUESTED** [review]
Looks good so far! Here's some changes to be made before I merge it in:

- For the x button, you could reuse Yeji's delete button under the CollegeBox component
- The way you have the empty space for the extracurriculars and interests are fine for now, I might ask the designers about adding text or some other indicator that people are supposed to press enter there later but don't worry about it for now
- For levels, can you make a drop down for National, State, and Regional? List might grow in the future but those are good for now
- Can you add a little bit more margin at the bottom of the page to match the design
- Designers had to add a "show contact on profile" toggle section on the page, so can you add the frontend for that as well (rip changes from clients)

Thanks! Lmk if you have more questions

**Comment by oliviasl** [comment]
Update from designers: For extracurriculars and interests in the text input can you add placeholder text saying "Type and press enter to add" thanks!

@mcho9434 @greydonokeefe

**Comment by greydono23** [comment]
@oliviasl just pushed all those edits^^

**Review by oliviasl — APPROVED** [review]
Looks great thanks!

**Pull request merged**
