### PR TITLE
Sprint 4: 4-AthenticationPage-Matt

### PR DESCRIPTION
**Pull request by mcho9434**
What changed:
- new paginated backend call
- fixes to navbar url handling(shit was appending lmao idek)
- Authentication Table+Row

no new dep
possible concerns: 
- might be able to chop renders with better logic, feel free to cr that
- pagination is just L/R model rn, but we could do the page numbers if you want, just didn't want to spend too much time on this

### CODE REVIEW

**Comment by mcho9434** [comment]
@oliviasl

**Comment by mcho9434** [comment]
man i spelled this shit wrong

**Review by oliviasl — CHANGES_REQUESTED** [review]
Looks great so far, the pagination functionality looks fine to me. Could you go back and try to apply more of the styles? Here's a list of some things I noticed need changing:
- Add the correct fonts (circular-std mostly)
- Left align the pagination
- Make the pagination match the color/font styles
I checked with designers and having it as "Page x of x" is fine, just make it match the original styles.

**Comment by mcho9434** [comment]
@oliviasl

**Review by oliviasl — APPROVED** [review]
LGTM, awesome work!

**Pull request merged**
