### PR TITLE
Sprint 8: Student Profile Variations + Socials Changes

### PR DESCRIPTION
**Pull request by chelyfern**
What changed:

- Created peer profile view and hooked up backend
- Enabled boolean showing of socials on peer profile view and student profile view

(4 views in total)
We have not created mentor view yet
We have not enabled cookies yet.

### CODE REVIEW

**Comment by chelyfern** [comment]
Cookies implemented!
Mentor view in progress

**Comment by chelyfern** [comment]
Screenshot 2024-03-30 at 9 36 23 PM
Screenshot 2024-03-30 at 9 49 20 PM
Screenshot 2024-03-30 at 9 46 46 PM
Screenshot 2024-03-30 at 9 37 22 PM
Screenshot 2024-03-30 at 9 36 48 PM

**Comment by chelyfern** [comment]
All 6 views done
Cookies are implemented

Notes box needs to be added to the mentor view and fixed in admin no socials
admin no socials
admin no socials
peer with socials
peer with socials
peer no socials
peer no socials
mentor no socials
mentor no socials
mentor w socials
mentor w socials
admin w socials
admin w socials

**Review by oliviasl — APPROVED** [review]
Awesome work!

**Pull request merged**
