### PR TITLE
Pagination is kinda working !!

### PR DESCRIPTION
**Pull request by chelyfern**
There may be bugs I need to fix

### CODE REVIEW

**Comment by oliviasl** [comment]
Screenshot 2024-02-13 at 7 45 42 PM
I think the pagination isn't displaying properly my end, the tabbing at the bottom increases but all of the entries display on the same page right now. Maybe take another look and let me know if it's working on your end

**Comment by oliviasl** [comment]
@chelyfern @kristenwon

**Comment by chelyfern** [comment]
https://www.loom.com/share/d8fecf243a1f4cd299fb700a8f6ac982?sid=e408d4a1-6a5c-42b6-8570-85722a2c7658

Fixed pagination almost

**Review by oliviasl — APPROVED** [review]
Nice work!

**Pull request merged**
