### PR TITLE
Sprint 5: Add College Validation/Backend

### PR DESCRIPTION
**Pull request by chroline**
**What changed:**
- added validations to form fields
- connected "add college" page to backend

### CODE REVIEW

**Review by oliviasl — CHANGES_REQUESTED** [review]
Nice job! I just have a few notes:
For form validation
- Add a min: 0, max: 1 for all percentages
- Add a min: 0 for gpa
- Right now the form doesn't submit unless you write something in additional notes, but I don't see a required member on the field so not quite sure why it's doing that. If you could look into that and make sure it can submit with an empty additional notes that would be great.
- If dates are empty, maybe pass some null value instead of "" because then the backend throws an type error and doesn't post the date
Those were all the things are caught, good work so far and lmk if you have any questions!

**Comment by chroline** [comment]
Thanks for catching those bugs!

Regarding the min/max for percentages, do you want the ranges to be 0–100 so users could enter the full percentage (i.e. "56")? Right now I have it set up so that whatever the user enters, that value gets divided by 100 before being sent to the backend (i.e. 56->.56). But I can change it to making the user enter the percentage as a decimal if you want it 0–1 (i.e. ".56").

**Comment by oliviasl** [comment]
Good question, let me ask the designers on the percentages and I'll get back to you! If we do end up doing a 0-100 range then we might need to add some text indicating it.

**Comment by oliviasl** [comment]
Ok 0-100 range is good for percentages is good, just make sure an error pops up when you're out of range.

**Comment by oliviasl** [comment]
In the most recent client meeting they said they wanted college name and main website to be mandatory for add/edit college, can you make that change as well? Thanks!

**Comment by chroline** [comment]
@oliviasl This should be good to go!

**Review by oliviasl — APPROVED** [review]
Awesome job!

**Pull request merged**
